### ISSUE TITLE
Release for 3.6.3?

### ISSUE THREAD

**Issue by AvangionQ** [HyperkineticAlot/ArchmageMod#1]
Oh, I love magic user classes ... this is really something to look forward to ... one thing, please make sure that your mod works with 3.6.3 when you release it ... I hope to be one of the first to try this out ... 🧙 https://github.com/kiooeht/ModTheSpire/releases

**Comment by HyperkineticAlot** [comment]
Thanks for the comment! I'm hoping to get the mod up and running within a month, but probably some more playtesting will ensue before I put it on the Workshop. If you'd like, I'd be more than happy to have another playtester.

Regarding 3.6.3 compatibility, I'm working within IntelliJ with a decompiled version of the latest ModTheSpire release through Steam, so it should certainly work with the newest version. (Unless for some reason the mod would work with the most recent version of BaseMod and MtS from the Workshop and not work with 3.6.3).
